version: '3.7'

services:
  api:
    build: ./backend
    container_name: api
    volumes:
      - ./backend:/usr/src/app/
    ports:
      - 5000:5000
    environment:
      - POINTR_EMAIL_PASSWORD=aa
      - POINTR_SERVER_SECRET=secret
      - SQLPassword=password
    depends_on:
      - db
    networks:
      - pointr
  front:
    build: ./frontend
    container_name: front
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app/
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - api
    networks:
      - pointr
  db:
    image: postgres:12-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pointrDB
    networks:
      - pointr

networks:
  pointr:
    driver: bridge
volumes:
  postgres_data:
