# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Setup npm package
        run: npm init -y && npm install
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./frontend
          env: secret=secret
          start: npm run serve
          wait-on: 'http://localhost:8080'
  backend:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python3 -m pip install --upgrade pip
        if [ -f ./requirements.txt ]; then pip3 install -r requirements.txt; fi
    - name: Run
      working-directory: ./backend
      run: python3 run.py dev
  # This workflow contains a single job called "build"
